### ISSUE TITLE
print text from the pdf

### ISSUE THREAD

**Issue by rpriyanshu9** [AlessioLuciani/flutter-pdf-text#10]
Hi, I'm unable to print text from the pdf. The error I get says that the path is not defined properly or is null. How to get the path of the file as a string?

**Comment by AlessioLuciani** [comment]
You can understand what the directories structure is using for example the FilePicker package and picking up a file. This way you can print its path directly from the File object.

**Comment by rpriyanshu9** [comment]
Thanks for the reply. I fixed the error above. But whenever I open more than one file using file picker I get a warning which is:
`W/PdfBox-Android(32241): Warning: You did not close a PDF Document`
I read the FAQs of Apache PDFBox, but there is no method named 'close()' in your package. If you can help me remove this warning it would be a great help.

**Comment by hicnar** [comment]
@rpriyanshu9 The warning "You did not close a PDF Document" issue is fixed in the most recent version of the plugin.

**Comment by AlessioLuciani** [comment]
Right, as @hicnar says, this issue has been solved.
